### DISCUSSION TITLE
Styling component parts (`::part()`)

### DISCUSSION THREAD

**Discussion by LeaVerou** [Devographics/surveys#148] [State of HTML Features]
A way to style shadow DOM elements that have opted in to being stylable from the outside.

### Code sample

```css
fancy-loader::part(loaded-bar) {
  background: var(--accent-color);
}
```

### MDN URL:

https://developer.mozilla.org/en-US/docs/Web/CSS/::part

### Specification URL:

https://www.w3.org/TR/css-shadow-parts-1/#part

### How stable is this feature?

Stable (Widely supported for several years)

### Type of feature

CSS

### What focus area does this feature fall under?

Consuming Web Components
